//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace MW.MComm.WalletSolution.MComm.MultiBank.Simulator {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="multiBankSoap", Namespace="http://tempuri.org/")]
    public partial class multiBank : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback listBanksOperationCompleted;
        
        private System.Threading.SendOrPostCallback accountInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback accountHistoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback customerInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback transferOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateBalanceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public multiBank() {
            this.Url = global::MW.MComm.WalletSolution.Properties.Settings.Default.MW_MComm_WalletSolution_MComm_Multibank_Simulator_multiBank;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event listBanksCompletedEventHandler listBanksCompleted;
        
        /// <remarks/>
        public event accountInfoCompletedEventHandler accountInfoCompleted;
        
        /// <remarks/>
        public event accountHistoryCompletedEventHandler accountHistoryCompleted;
        
        /// <remarks/>
        public event customerInfoCompletedEventHandler customerInfoCompleted;
        
        /// <remarks/>
        public event transferCompletedEventHandler transferCompleted;
        
        /// <remarks/>
        public event UpdateBalanceCompletedEventHandler UpdateBalanceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listBanks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BankQueryResult listBanks() {
            object[] results = this.Invoke("listBanks", new object[0]);
            return ((BankQueryResult)(results[0]));
        }
        
        /// <remarks/>
        public void listBanksAsync() {
            this.listBanksAsync(null);
        }
        
        /// <remarks/>
        public void listBanksAsync(object userState) {
            if ((this.listBanksOperationCompleted == null)) {
                this.listBanksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistBanksOperationCompleted);
            }
            this.InvokeAsync("listBanks", new object[0], this.listBanksOperationCompleted, userState);
        }
        
        private void OnlistBanksOperationCompleted(object arg) {
            if ((this.listBanksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listBanksCompleted(this, new listBanksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/accountInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccountQueryResult accountInfo(System.Guid BankId, string CustomerCode, string AccountCode) {
            object[] results = this.Invoke("accountInfo", new object[] {
                        BankId,
                        CustomerCode,
                        AccountCode});
            return ((AccountQueryResult)(results[0]));
        }
        
        /// <remarks/>
        public void accountInfoAsync(System.Guid BankId, string CustomerCode, string AccountCode) {
            this.accountInfoAsync(BankId, CustomerCode, AccountCode, null);
        }
        
        /// <remarks/>
        public void accountInfoAsync(System.Guid BankId, string CustomerCode, string AccountCode, object userState) {
            if ((this.accountInfoOperationCompleted == null)) {
                this.accountInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaccountInfoOperationCompleted);
            }
            this.InvokeAsync("accountInfo", new object[] {
                        BankId,
                        CustomerCode,
                        AccountCode}, this.accountInfoOperationCompleted, userState);
        }
        
        private void OnaccountInfoOperationCompleted(object arg) {
            if ((this.accountInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.accountInfoCompleted(this, new accountInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/accountHistory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HistoryQueryResult accountHistory(System.Guid BankId, string CustomerCode, string AccountCode) {
            object[] results = this.Invoke("accountHistory", new object[] {
                        BankId,
                        CustomerCode,
                        AccountCode});
            return ((HistoryQueryResult)(results[0]));
        }
        
        /// <remarks/>
        public void accountHistoryAsync(System.Guid BankId, string CustomerCode, string AccountCode) {
            this.accountHistoryAsync(BankId, CustomerCode, AccountCode, null);
        }
        
        /// <remarks/>
        public void accountHistoryAsync(System.Guid BankId, string CustomerCode, string AccountCode, object userState) {
            if ((this.accountHistoryOperationCompleted == null)) {
                this.accountHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaccountHistoryOperationCompleted);
            }
            this.InvokeAsync("accountHistory", new object[] {
                        BankId,
                        CustomerCode,
                        AccountCode}, this.accountHistoryOperationCompleted, userState);
        }
        
        private void OnaccountHistoryOperationCompleted(object arg) {
            if ((this.accountHistoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.accountHistoryCompleted(this, new accountHistoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/customerInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomerQueryResult customerInfo(System.Guid BankId, string CustomerCode) {
            object[] results = this.Invoke("customerInfo", new object[] {
                        BankId,
                        CustomerCode});
            return ((CustomerQueryResult)(results[0]));
        }
        
        /// <remarks/>
        public void customerInfoAsync(System.Guid BankId, string CustomerCode) {
            this.customerInfoAsync(BankId, CustomerCode, null);
        }
        
        /// <remarks/>
        public void customerInfoAsync(System.Guid BankId, string CustomerCode, object userState) {
            if ((this.customerInfoOperationCompleted == null)) {
                this.customerInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncustomerInfoOperationCompleted);
            }
            this.InvokeAsync("customerInfo", new object[] {
                        BankId,
                        CustomerCode}, this.customerInfoOperationCompleted, userState);
        }
        
        private void OncustomerInfoOperationCompleted(object arg) {
            if ((this.customerInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.customerInfoCompleted(this, new customerInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/transfer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransferResult transfer(System.Guid SenderBank, string SenderCode, string SenderAccount, System.Guid ReceiverBank, string ReceiverCode, string ReceiverAccount, decimal Amount, string Currency, string Memo) {
            object[] results = this.Invoke("transfer", new object[] {
                        SenderBank,
                        SenderCode,
                        SenderAccount,
                        ReceiverBank,
                        ReceiverCode,
                        ReceiverAccount,
                        Amount,
                        Currency,
                        Memo});
            return ((TransferResult)(results[0]));
        }
        
        /// <remarks/>
        public void transferAsync(System.Guid SenderBank, string SenderCode, string SenderAccount, System.Guid ReceiverBank, string ReceiverCode, string ReceiverAccount, decimal Amount, string Currency, string Memo) {
            this.transferAsync(SenderBank, SenderCode, SenderAccount, ReceiverBank, ReceiverCode, ReceiverAccount, Amount, Currency, Memo, null);
        }
        
        /// <remarks/>
        public void transferAsync(System.Guid SenderBank, string SenderCode, string SenderAccount, System.Guid ReceiverBank, string ReceiverCode, string ReceiverAccount, decimal Amount, string Currency, string Memo, object userState) {
            if ((this.transferOperationCompleted == null)) {
                this.transferOperationCompleted = new System.Threading.SendOrPostCallback(this.OntransferOperationCompleted);
            }
            this.InvokeAsync("transfer", new object[] {
                        SenderBank,
                        SenderCode,
                        SenderAccount,
                        ReceiverBank,
                        ReceiverCode,
                        ReceiverAccount,
                        Amount,
                        Currency,
                        Memo}, this.transferOperationCompleted, userState);
        }
        
        private void OntransferOperationCompleted(object arg) {
            if ((this.transferCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transferCompleted(this, new transferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateBalance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransferResult UpdateBalance(System.Guid BankId, string CustomerCode, string AccountCode, decimal Amount, string Memo, string Description) {
            object[] results = this.Invoke("UpdateBalance", new object[] {
                        BankId,
                        CustomerCode,
                        AccountCode,
                        Amount,
                        Memo,
                        Description});
            return ((TransferResult)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateBalanceAsync(System.Guid BankId, string CustomerCode, string AccountCode, decimal Amount, string Memo, string Description) {
            this.UpdateBalanceAsync(BankId, CustomerCode, AccountCode, Amount, Memo, Description, null);
        }
        
        /// <remarks/>
        public void UpdateBalanceAsync(System.Guid BankId, string CustomerCode, string AccountCode, decimal Amount, string Memo, string Description, object userState) {
            if ((this.UpdateBalanceOperationCompleted == null)) {
                this.UpdateBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateBalanceOperationCompleted);
            }
            this.InvokeAsync("UpdateBalance", new object[] {
                        BankId,
                        CustomerCode,
                        AccountCode,
                        Amount,
                        Memo,
                        Description}, this.UpdateBalanceOperationCompleted, userState);
        }
        
        private void OnUpdateBalanceOperationCompleted(object arg) {
            if ((this.UpdateBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateBalanceCompleted(this, new UpdateBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BankQueryResult {
        
        private int erroCodeField;
        
        private string errorTextField;
        
        private bank[] banksField;
        
        /// <remarks/>
        public int ErroCode {
            get {
                return this.erroCodeField;
            }
            set {
                this.erroCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public bank[] Banks {
            get {
                return this.banksField;
            }
            set {
                this.banksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class bank {
        
        private System.Guid bankIdField;
        
        private string bankNameField;
        
        private string defaultCurrencyField;
        
        /// <remarks/>
        public System.Guid BankId {
            get {
                return this.bankIdField;
            }
            set {
                this.bankIdField = value;
            }
        }
        
        /// <remarks/>
        public string BankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
            }
        }
        
        /// <remarks/>
        public string DefaultCurrency {
            get {
                return this.defaultCurrencyField;
            }
            set {
                this.defaultCurrencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TransferResult {
        
        private int errorCodeField;
        
        private string errorTextField;
        
        private account newBalanceSenderField;
        
        private account newBalanceReceiverField;
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
            }
        }
        
        /// <remarks/>
        public account NewBalanceSender {
            get {
                return this.newBalanceSenderField;
            }
            set {
                this.newBalanceSenderField = value;
            }
        }
        
        /// <remarks/>
        public account NewBalanceReceiver {
            get {
                return this.newBalanceReceiverField;
            }
            set {
                this.newBalanceReceiverField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class account {
        
        private System.Guid bankIdField;
        
        private string bankNameField;
        
        private string customerCodeField;
        
        private string customerNameField;
        
        private string accountCodeField;
        
        private string accountCurrencyField;
        
        private decimal accountBalanceField;
        
        /// <remarks/>
        public System.Guid BankId {
            get {
                return this.bankIdField;
            }
            set {
                this.bankIdField = value;
            }
        }
        
        /// <remarks/>
        public string BankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerCode {
            get {
                return this.customerCodeField;
            }
            set {
                this.customerCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string AccountCode {
            get {
                return this.accountCodeField;
            }
            set {
                this.accountCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AccountCurrency {
            get {
                return this.accountCurrencyField;
            }
            set {
                this.accountCurrencyField = value;
            }
        }
        
        /// <remarks/>
        public decimal AccountBalance {
            get {
                return this.accountBalanceField;
            }
            set {
                this.accountBalanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerQueryResult {
        
        private int erroCodeField;
        
        private string errorTextField;
        
        private account[] accountsField;
        
        /// <remarks/>
        public int ErroCode {
            get {
                return this.erroCodeField;
            }
            set {
                this.erroCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public account[] Accounts {
            get {
                return this.accountsField;
            }
            set {
                this.accountsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class accountDetail {
        
        private System.DateTime timeDateField;
        
        private string descriptionField;
        
        private decimal amountField;
        
        private decimal balanceField;
        
        private string memoField;
        
        /// <remarks/>
        public System.DateTime TimeDate {
            get {
                return this.timeDateField;
            }
            set {
                this.timeDateField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public decimal Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HistoryQueryResult {
        
        private int erroCodeField;
        
        private string errorTextField;
        
        private account accountdataField;
        
        private accountDetail[] detailField;
        
        /// <remarks/>
        public int ErroCode {
            get {
                return this.erroCodeField;
            }
            set {
                this.erroCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
            }
        }
        
        /// <remarks/>
        public account Accountdata {
            get {
                return this.accountdataField;
            }
            set {
                this.accountdataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public accountDetail[] Detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountQueryResult {
        
        private int erroCodeField;
        
        private string errorTextField;
        
        private account accountdataField;
        
        /// <remarks/>
        public int ErroCode {
            get {
                return this.erroCodeField;
            }
            set {
                this.erroCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
            }
        }
        
        /// <remarks/>
        public account Accountdata {
            get {
                return this.accountdataField;
            }
            set {
                this.accountdataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void listBanksCompletedEventHandler(object sender, listBanksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listBanksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listBanksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BankQueryResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BankQueryResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void accountInfoCompletedEventHandler(object sender, accountInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class accountInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal accountInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccountQueryResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccountQueryResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void accountHistoryCompletedEventHandler(object sender, accountHistoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class accountHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal accountHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HistoryQueryResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HistoryQueryResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void customerInfoCompletedEventHandler(object sender, customerInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class customerInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal customerInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerQueryResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerQueryResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void transferCompletedEventHandler(object sender, transferCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transferCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transferCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransferResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransferResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void UpdateBalanceCompletedEventHandler(object sender, UpdateBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransferResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransferResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591