//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591
namespace MW.MComm.WalletSolution.MComm.SMS.SMSSender {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="smsSenderSoap", Namespace="http://skill3.com/webservices/sms2006/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusinessObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StatusObject))]
    public partial class smsSender : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback sendSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback pushWAPOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public smsSender() {
            this.Url = global::MW.MComm.WalletSolution.Properties.Settings.Default.MW_MComm_WalletSolution_MComm_SMS_SMSSender_smsSender;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event sendSMSCompletedEventHandler sendSMSCompleted;
        
        /// <remarks/>
        public event pushWAPCompletedEventHandler pushWAPCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://skill3.com/webservices/sms2006/sendSMS", RequestNamespace="http://skill3.com/webservices/sms2006/", ResponseNamespace="http://skill3.com/webservices/sms2006/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OutgoingSMSResults sendSMS(string sender, string receiver, string text) {
            object[] results = this.Invoke("sendSMS", new object[] {
                        sender,
                        receiver,
                        text});
            return ((OutgoingSMSResults)(results[0]));
        }
        
        /// <remarks/>
        public void sendSMSAsync(string sender, string receiver, string text) {
            this.sendSMSAsync(sender, receiver, text, null);
        }
        
        /// <remarks/>
        public void sendSMSAsync(string sender, string receiver, string text, object userState) {
            if ((this.sendSMSOperationCompleted == null)) {
                this.sendSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendSMSOperationCompleted);
            }
            this.InvokeAsync("sendSMS", new object[] {
                        sender,
                        receiver,
                        text}, this.sendSMSOperationCompleted, userState);
        }
        
        private void OnsendSMSOperationCompleted(object arg) {
            if ((this.sendSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendSMSCompleted(this, new sendSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://skill3.com/webservices/sms2006/pushWAP", RequestNamespace="http://skill3.com/webservices/sms2006/", ResponseNamespace="http://skill3.com/webservices/sms2006/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OutgoingSMSResults pushWAP(string sender, string receiver, string text, string WapUrl) {
            object[] results = this.Invoke("pushWAP", new object[] {
                        sender,
                        receiver,
                        text,
                        WapUrl});
            return ((OutgoingSMSResults)(results[0]));
        }
        
        /// <remarks/>
        public void pushWAPAsync(string sender, string receiver, string text, string WapUrl) {
            this.pushWAPAsync(sender, receiver, text, WapUrl, null);
        }
        
        /// <remarks/>
        public void pushWAPAsync(string sender, string receiver, string text, string WapUrl, object userState) {
            if ((this.pushWAPOperationCompleted == null)) {
                this.pushWAPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpushWAPOperationCompleted);
            }
            this.InvokeAsync("pushWAP", new object[] {
                        sender,
                        receiver,
                        text,
                        WapUrl}, this.pushWAPOperationCompleted, userState);
        }
        
        private void OnpushWAPOperationCompleted(object arg) {
            if ((this.pushWAPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pushWAPCompleted(this, new pushWAPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skill3.com/webservices/sms2006/")]
    public partial class OutgoingSMSResults : StatusObject {
        
        private OutgoingSMS[] resultsField;
        
        /// <remarks/>
        public OutgoingSMS[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skill3.com/webservices/sms2006/")]
    public partial class OutgoingSMS : PersistedBusinessObject {
        
        private string senderField;
        
        private string receiverField;
        
        private string nowSMSServerField;
        
        private string sMSContentField;
        
        private string serverResponseField;
        
        private long internalIDField;
        
        private string primaryKeyField;
        
        private string primaryNameField;
        
        private string primaryIndexField;
        
        private string primarySortColumnField;
        
        public OutgoingSMS() {
            this.senderField = "";
            this.receiverField = "";
            this.nowSMSServerField = "";
            this.sMSContentField = "";
            this.serverResponseField = "";
            this.internalIDField = ((long)(0));
            this.primaryKeyField = "";
            this.primaryNameField = "";
            this.primaryIndexField = "";
            this.primarySortColumnField = "";
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string NowSMSServer {
            get {
                return this.nowSMSServerField;
            }
            set {
                this.nowSMSServerField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string SMSContent {
            get {
                return this.sMSContentField;
            }
            set {
                this.sMSContentField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string ServerResponse {
            get {
                return this.serverResponseField;
            }
            set {
                this.serverResponseField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "0")]
        public long InternalID {
            get {
                return this.internalIDField;
            }
            set {
                this.internalIDField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string PrimaryKey {
            get {
                return this.primaryKeyField;
            }
            set {
                this.primaryKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string PrimaryName {
            get {
                return this.primaryNameField;
            }
            set {
                this.primaryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string PrimaryIndex {
            get {
                return this.primaryIndexField;
            }
            set {
                this.primaryIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string PrimarySortColumn {
            get {
                return this.primarySortColumnField;
            }
            set {
                this.primarySortColumnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OutgoingSMS))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skill3.com/webservices/sms2006/")]
    public partial class PersistedBusinessObject : BusinessObject {
        
        private System.Nullable<System.Guid> createdByUserIDField;
        
        private System.Nullable<System.DateTime> createdDateField;
        
        private System.Nullable<System.Guid> lastModifiedByUserIDField;
        
        private System.Nullable<System.DateTime> lastModifiedDateField;
        
        private byte[] timestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> CreatedByUserID {
            get {
                return this.createdByUserIDField;
            }
            set {
                this.createdByUserIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> LastModifiedByUserID {
            get {
                return this.lastModifiedByUserIDField;
            }
            set {
                this.lastModifiedByUserIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersistedBusinessObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OutgoingSMS))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skill3.com/webservices/sms2006/")]
    public partial class BusinessObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OutgoingSMSResults))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skill3.com/webservices/sms2006/")]
    public partial class StatusObject {
        
        private int statusCodeField;
        
        private string statusDescriptionField;
        
        private int totalRecordsField;
        
        private bool maximumListSizeExceededField;
        
        public StatusObject() {
            this.statusDescriptionField = "";
        }
        
        /// <remarks/>
        public int StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int TotalRecords {
            get {
                return this.totalRecordsField;
            }
            set {
                this.totalRecordsField = value;
            }
        }
        
        /// <remarks/>
        public bool MaximumListSizeExceeded {
            get {
                return this.maximumListSizeExceededField;
            }
            set {
                this.maximumListSizeExceededField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void sendSMSCompletedEventHandler(object sender, sendSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OutgoingSMSResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OutgoingSMSResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void pushWAPCompletedEventHandler(object sender, pushWAPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pushWAPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pushWAPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OutgoingSMSResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OutgoingSMSResults)(this.results[0]));
            }
        }
    }
}
#pragma warning restore 1591