//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MW.MComm.WalletSolution.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://216.184.113.85/W.MComm.SMS.WebService/smsSender.asmx")]
        public string MW_MComm_WalletSolution_MComm_SMS_SMSSender_smsSender {
            get {
                return ((string)(this["MW_MComm_WalletSolution_MComm_SMS_SMSSender_smsSender"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://216.184.113.85/MW.MComm.Nuevatel.WebService/service1.asmx")]
        public string MW_MComm_WalletSolution_MComm_Nuevatel_CustomerManager_Service1 {
            get {
                return ((string)(this["MW_MComm_WalletSolution_MComm_Nuevatel_CustomerManager_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://216.184.113.85/satmlBypass/requestAproval.asmx")]
        public string MW_MComm_WalletSolution_MComm_SMS_RequestApproval_requestAproval {
            get {
                return ((string)(this["MW_MComm_WalletSolution_MComm_SMS_RequestApproval_requestAproval"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://216.184.113.58:8080/ServiceWS/ClientInformation")]
        public string MW_MComm_WalletSolution_MComm_Nuevatel_ClientInformation_ClientInfoService {
            get {
                return ((string)(this["MW_MComm_WalletSolution_MComm_Nuevatel_ClientInformation_ClientInfoService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1/MW.MComm.GanaderoSim.WebService/Service.asmx")]
        public string MW_MComm_WalletSolution_MComm_Ganadero_Simulator_Service {
            get {
                return ((string)(this["MW_MComm_WalletSolution_MComm_Ganadero_Simulator_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1/MW.MComm.SMS.WebService/smsSender.asmx")]
        public string MW_MComm_WalletSolution_MComm_SMS_SMSSenderUSA_smsSender {
            get {
                return ((string)(this["MW_MComm_WalletSolution_MComm_SMS_SMSSenderUSA_smsSender"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/MW.MComm.CarrierSim.WebService/Customers/PhoneManager.asmx")]
        public string MW_MComm_WalletSolution_MComm_CarrierSim_PhoneManager_PhoneManager {
            get {
                return ((string)(this["MW_MComm_WalletSolution_MComm_CarrierSim_PhoneManager_PhoneManager"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/MW.MComm.CarrierSim.WebService/Customers/CustomerManager.asmx")]
        public string MW_MComm_WalletSolution_MComm_CarrierSim_CustomerManager_CustomerManager {
            get {
                return ((string)(this["MW_MComm_WalletSolution_MComm_CarrierSim_CustomerManager_CustomerManager"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/MW.MComm.GanaderoSim.WebService/multiBank.asmx")]
        public string MW_MComm_WalletSolution_MComm_Multibank_Simulator_multiBank {
            get {
                return ((string)(this["MW_MComm_WalletSolution_MComm_Multibank_Simulator_multiBank"]));
            }
        }
    }
}
