//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591
namespace MW.MComm.WalletSolution.MComm.Nuevatel.CustomerManager {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback wsbalanceEnquiry1OperationCompleted;
        
        private System.Threading.SendOrPostCallback wsbalanceEnquiry2OperationCompleted;
        
        private System.Threading.SendOrPostCallback wsbalanceEnquiry3OperationCompleted;
        
        private System.Threading.SendOrPostCallback wsbalanceEnquiry4OperationCompleted;
        
        private System.Threading.SendOrPostCallback wsbalanceDiscount1OperationCompleted;
        
        private System.Threading.SendOrPostCallback wsbalanceDiscount2OperationCompleted;
        
        private System.Threading.SendOrPostCallback wsAddCreditOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::MW.MComm.WalletSolution.Properties.Settings.Default.MW_MComm_WalletSolution_MComm_Nuevatel_CustomerManager_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event wsbalanceEnquiry1CompletedEventHandler wsbalanceEnquiry1Completed;
        
        /// <remarks/>
        public event wsbalanceEnquiry2CompletedEventHandler wsbalanceEnquiry2Completed;
        
        /// <remarks/>
        public event wsbalanceEnquiry3CompletedEventHandler wsbalanceEnquiry3Completed;
        
        /// <remarks/>
        public event wsbalanceEnquiry4CompletedEventHandler wsbalanceEnquiry4Completed;
        
        /// <remarks/>
        public event wsbalanceDiscount1CompletedEventHandler wsbalanceDiscount1Completed;
        
        /// <remarks/>
        public event wsbalanceDiscount2CompletedEventHandler wsbalanceDiscount2Completed;
        
        /// <remarks/>
        public event wsAddCreditCompletedEventHandler wsAddCreditCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsbalanceEnquiry1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public balance1Response wsbalanceEnquiry1(string PhoneNumber, string TransactionId) {
            object[] results = this.Invoke("wsbalanceEnquiry1", new object[] {
                        PhoneNumber,
                        TransactionId});
            return ((balance1Response)(results[0]));
        }
        
        /// <remarks/>
        public void wsbalanceEnquiry1Async(string PhoneNumber, string TransactionId) {
            this.wsbalanceEnquiry1Async(PhoneNumber, TransactionId, null);
        }
        
        /// <remarks/>
        public void wsbalanceEnquiry1Async(string PhoneNumber, string TransactionId, object userState) {
            if ((this.wsbalanceEnquiry1OperationCompleted == null)) {
                this.wsbalanceEnquiry1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsbalanceEnquiry1OperationCompleted);
            }
            this.InvokeAsync("wsbalanceEnquiry1", new object[] {
                        PhoneNumber,
                        TransactionId}, this.wsbalanceEnquiry1OperationCompleted, userState);
        }
        
        private void OnwsbalanceEnquiry1OperationCompleted(object arg) {
            if ((this.wsbalanceEnquiry1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsbalanceEnquiry1Completed(this, new wsbalanceEnquiry1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsbalanceEnquiry2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public balance2Response wsbalanceEnquiry2(string PhoneNumber, string TransactionId) {
            object[] results = this.Invoke("wsbalanceEnquiry2", new object[] {
                        PhoneNumber,
                        TransactionId});
            return ((balance2Response)(results[0]));
        }
        
        /// <remarks/>
        public void wsbalanceEnquiry2Async(string PhoneNumber, string TransactionId) {
            this.wsbalanceEnquiry2Async(PhoneNumber, TransactionId, null);
        }
        
        /// <remarks/>
        public void wsbalanceEnquiry2Async(string PhoneNumber, string TransactionId, object userState) {
            if ((this.wsbalanceEnquiry2OperationCompleted == null)) {
                this.wsbalanceEnquiry2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsbalanceEnquiry2OperationCompleted);
            }
            this.InvokeAsync("wsbalanceEnquiry2", new object[] {
                        PhoneNumber,
                        TransactionId}, this.wsbalanceEnquiry2OperationCompleted, userState);
        }
        
        private void OnwsbalanceEnquiry2OperationCompleted(object arg) {
            if ((this.wsbalanceEnquiry2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsbalanceEnquiry2Completed(this, new wsbalanceEnquiry2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsbalanceEnquiry3", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public balance3Response wsbalanceEnquiry3(string PhoneNumber, string TransactionId, decimal Ammount) {
            object[] results = this.Invoke("wsbalanceEnquiry3", new object[] {
                        PhoneNumber,
                        TransactionId,
                        Ammount});
            return ((balance3Response)(results[0]));
        }
        
        /// <remarks/>
        public void wsbalanceEnquiry3Async(string PhoneNumber, string TransactionId, decimal Ammount) {
            this.wsbalanceEnquiry3Async(PhoneNumber, TransactionId, Ammount, null);
        }
        
        /// <remarks/>
        public void wsbalanceEnquiry3Async(string PhoneNumber, string TransactionId, decimal Ammount, object userState) {
            if ((this.wsbalanceEnquiry3OperationCompleted == null)) {
                this.wsbalanceEnquiry3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsbalanceEnquiry3OperationCompleted);
            }
            this.InvokeAsync("wsbalanceEnquiry3", new object[] {
                        PhoneNumber,
                        TransactionId,
                        Ammount}, this.wsbalanceEnquiry3OperationCompleted, userState);
        }
        
        private void OnwsbalanceEnquiry3OperationCompleted(object arg) {
            if ((this.wsbalanceEnquiry3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsbalanceEnquiry3Completed(this, new wsbalanceEnquiry3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsbalanceEnquiry4", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public balance4Response wsbalanceEnquiry4(string PhoneNumber, string TransactionId) {
            object[] results = this.Invoke("wsbalanceEnquiry4", new object[] {
                        PhoneNumber,
                        TransactionId});
            return ((balance4Response)(results[0]));
        }
        
        /// <remarks/>
        public void wsbalanceEnquiry4Async(string PhoneNumber, string TransactionId) {
            this.wsbalanceEnquiry4Async(PhoneNumber, TransactionId, null);
        }
        
        /// <remarks/>
        public void wsbalanceEnquiry4Async(string PhoneNumber, string TransactionId, object userState) {
            if ((this.wsbalanceEnquiry4OperationCompleted == null)) {
                this.wsbalanceEnquiry4OperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsbalanceEnquiry4OperationCompleted);
            }
            this.InvokeAsync("wsbalanceEnquiry4", new object[] {
                        PhoneNumber,
                        TransactionId}, this.wsbalanceEnquiry4OperationCompleted, userState);
        }
        
        private void OnwsbalanceEnquiry4OperationCompleted(object arg) {
            if ((this.wsbalanceEnquiry4Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsbalanceEnquiry4Completed(this, new wsbalanceEnquiry4CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsbalanceDiscount1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public discount1Response wsbalanceDiscount1(string PhoneNumber, string TransactionId, decimal Ammount) {
            object[] results = this.Invoke("wsbalanceDiscount1", new object[] {
                        PhoneNumber,
                        TransactionId,
                        Ammount});
            return ((discount1Response)(results[0]));
        }
        
        /// <remarks/>
        public void wsbalanceDiscount1Async(string PhoneNumber, string TransactionId, decimal Ammount) {
            this.wsbalanceDiscount1Async(PhoneNumber, TransactionId, Ammount, null);
        }
        
        /// <remarks/>
        public void wsbalanceDiscount1Async(string PhoneNumber, string TransactionId, decimal Ammount, object userState) {
            if ((this.wsbalanceDiscount1OperationCompleted == null)) {
                this.wsbalanceDiscount1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsbalanceDiscount1OperationCompleted);
            }
            this.InvokeAsync("wsbalanceDiscount1", new object[] {
                        PhoneNumber,
                        TransactionId,
                        Ammount}, this.wsbalanceDiscount1OperationCompleted, userState);
        }
        
        private void OnwsbalanceDiscount1OperationCompleted(object arg) {
            if ((this.wsbalanceDiscount1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsbalanceDiscount1Completed(this, new wsbalanceDiscount1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsbalanceDiscount2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public discount2Response wsbalanceDiscount2(string PhoneNumber, string TransactionId, string TariffCode) {
            object[] results = this.Invoke("wsbalanceDiscount2", new object[] {
                        PhoneNumber,
                        TransactionId,
                        TariffCode});
            return ((discount2Response)(results[0]));
        }
        
        /// <remarks/>
        public void wsbalanceDiscount2Async(string PhoneNumber, string TransactionId, string TariffCode) {
            this.wsbalanceDiscount2Async(PhoneNumber, TransactionId, TariffCode, null);
        }
        
        /// <remarks/>
        public void wsbalanceDiscount2Async(string PhoneNumber, string TransactionId, string TariffCode, object userState) {
            if ((this.wsbalanceDiscount2OperationCompleted == null)) {
                this.wsbalanceDiscount2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsbalanceDiscount2OperationCompleted);
            }
            this.InvokeAsync("wsbalanceDiscount2", new object[] {
                        PhoneNumber,
                        TransactionId,
                        TariffCode}, this.wsbalanceDiscount2OperationCompleted, userState);
        }
        
        private void OnwsbalanceDiscount2OperationCompleted(object arg) {
            if ((this.wsbalanceDiscount2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsbalanceDiscount2Completed(this, new wsbalanceDiscount2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsAddCredit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public addCreditResponse wsAddCredit(string PhoneNumber, string TransactionId, decimal Ammount, string FiscalName, string FiscalId, string MachineId) {
            object[] results = this.Invoke("wsAddCredit", new object[] {
                        PhoneNumber,
                        TransactionId,
                        Ammount,
                        FiscalName,
                        FiscalId,
                        MachineId});
            return ((addCreditResponse)(results[0]));
        }
        
        /// <remarks/>
        public void wsAddCreditAsync(string PhoneNumber, string TransactionId, decimal Ammount, string FiscalName, string FiscalId, string MachineId) {
            this.wsAddCreditAsync(PhoneNumber, TransactionId, Ammount, FiscalName, FiscalId, MachineId, null);
        }
        
        /// <remarks/>
        public void wsAddCreditAsync(string PhoneNumber, string TransactionId, decimal Ammount, string FiscalName, string FiscalId, string MachineId, object userState) {
            if ((this.wsAddCreditOperationCompleted == null)) {
                this.wsAddCreditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsAddCreditOperationCompleted);
            }
            this.InvokeAsync("wsAddCredit", new object[] {
                        PhoneNumber,
                        TransactionId,
                        Ammount,
                        FiscalName,
                        FiscalId,
                        MachineId}, this.wsAddCreditOperationCompleted, userState);
        }
        
        private void OnwsAddCreditOperationCompleted(object arg) {
            if ((this.wsAddCreditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsAddCreditCompleted(this, new wsAddCreditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class balance1Response {
        
        private decimal balanceField;
        
        private string transactionIdField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private string fullResponseField;
        
        private string fullRequestField;
        
        /// <remarks/>
        public decimal balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string fullResponse {
            get {
                return this.fullResponseField;
            }
            set {
                this.fullResponseField = value;
            }
        }
        
        /// <remarks/>
        public string fullRequest {
            get {
                return this.fullRequestField;
            }
            set {
                this.fullRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class addCreditResponse {
        
        private string transactionIdField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private string fullResponseField;
        
        private string fullRequestField;
        
        private string successField;
        
        private string fiscalIdField;
        
        private string invoiceNumberField;
        
        private string orderNumberField;
        
        private string invoiceSerialNumberField;
        
        private string companyNameField;
        
        private string expirationDateLiteralSpanishField;
        
        /// <remarks/>
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string fullResponse {
            get {
                return this.fullResponseField;
            }
            set {
                this.fullResponseField = value;
            }
        }
        
        /// <remarks/>
        public string fullRequest {
            get {
                return this.fullRequestField;
            }
            set {
                this.fullRequestField = value;
            }
        }
        
        /// <remarks/>
        public string success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string fiscalId {
            get {
                return this.fiscalIdField;
            }
            set {
                this.fiscalIdField = value;
            }
        }
        
        /// <remarks/>
        public string invoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string orderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
            }
        }
        
        /// <remarks/>
        public string invoiceSerialNumber {
            get {
                return this.invoiceSerialNumberField;
            }
            set {
                this.invoiceSerialNumberField = value;
            }
        }
        
        /// <remarks/>
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string expirationDateLiteralSpanish {
            get {
                return this.expirationDateLiteralSpanishField;
            }
            set {
                this.expirationDateLiteralSpanishField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class discount2Response {
        
        private string transactionIdField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private string fullResponseField;
        
        private string fullRequestField;
        
        private string successField;
        
        /// <remarks/>
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string fullResponse {
            get {
                return this.fullResponseField;
            }
            set {
                this.fullResponseField = value;
            }
        }
        
        /// <remarks/>
        public string fullRequest {
            get {
                return this.fullRequestField;
            }
            set {
                this.fullRequestField = value;
            }
        }
        
        /// <remarks/>
        public string success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class discount1Response {
        
        private string transactionIdField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private string fullResponseField;
        
        private string fullRequestField;
        
        private string successField;
        
        /// <remarks/>
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string fullResponse {
            get {
                return this.fullResponseField;
            }
            set {
                this.fullResponseField = value;
            }
        }
        
        /// <remarks/>
        public string fullRequest {
            get {
                return this.fullRequestField;
            }
            set {
                this.fullRequestField = value;
            }
        }
        
        /// <remarks/>
        public string success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class balance4Response {
        
        private string transactionIdField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private string fullResponseField;
        
        private string fullRequestField;
        
        private decimal balanceField;
        
        private string expirationDateField;
        
        private string freeMinutesField;
        
        private string freeSecondsField;
        
        private string balance1Field;
        
        private string expirationDate1Field;
        
        private string balance2Field;
        
        private string expirationDate2Field;
        
        private string planField;
        
        private string serviceProviderField;
        
        private string stateField;
        
        /// <remarks/>
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string fullResponse {
            get {
                return this.fullResponseField;
            }
            set {
                this.fullResponseField = value;
            }
        }
        
        /// <remarks/>
        public string fullRequest {
            get {
                return this.fullRequestField;
            }
            set {
                this.fullRequestField = value;
            }
        }
        
        /// <remarks/>
        public decimal balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        public string expirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        public string freeMinutes {
            get {
                return this.freeMinutesField;
            }
            set {
                this.freeMinutesField = value;
            }
        }
        
        /// <remarks/>
        public string freeSeconds {
            get {
                return this.freeSecondsField;
            }
            set {
                this.freeSecondsField = value;
            }
        }
        
        /// <remarks/>
        public string balance1 {
            get {
                return this.balance1Field;
            }
            set {
                this.balance1Field = value;
            }
        }
        
        /// <remarks/>
        public string expirationDate1 {
            get {
                return this.expirationDate1Field;
            }
            set {
                this.expirationDate1Field = value;
            }
        }
        
        /// <remarks/>
        public string balance2 {
            get {
                return this.balance2Field;
            }
            set {
                this.balance2Field = value;
            }
        }
        
        /// <remarks/>
        public string expirationDate2 {
            get {
                return this.expirationDate2Field;
            }
            set {
                this.expirationDate2Field = value;
            }
        }
        
        /// <remarks/>
        public string plan {
            get {
                return this.planField;
            }
            set {
                this.planField = value;
            }
        }
        
        /// <remarks/>
        public string serviceProvider {
            get {
                return this.serviceProviderField;
            }
            set {
                this.serviceProviderField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class balance3Response {
        
        private string transactionIdField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private string fullResponseField;
        
        private string fullRequestField;
        
        private string enoughCreditField;
        
        /// <remarks/>
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string fullResponse {
            get {
                return this.fullResponseField;
            }
            set {
                this.fullResponseField = value;
            }
        }
        
        /// <remarks/>
        public string fullRequest {
            get {
                return this.fullRequestField;
            }
            set {
                this.fullRequestField = value;
            }
        }
        
        /// <remarks/>
        public string enoughCredit {
            get {
                return this.enoughCreditField;
            }
            set {
                this.enoughCreditField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class balance2Response {
        
        private string transactionIdField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private string fullResponseField;
        
        private string fullRequestField;
        
        private decimal balanceField;
        
        private string expirationDateField;
        
        private string freeMinutesField;
        
        private string freeSecondsField;
        
        private string balance1Field;
        
        private string expirationDate1Field;
        
        private string balance2Field;
        
        private string expirationDate2Field;
        
        private string planField;
        
        /// <remarks/>
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string fullResponse {
            get {
                return this.fullResponseField;
            }
            set {
                this.fullResponseField = value;
            }
        }
        
        /// <remarks/>
        public string fullRequest {
            get {
                return this.fullRequestField;
            }
            set {
                this.fullRequestField = value;
            }
        }
        
        /// <remarks/>
        public decimal balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        public string expirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        public string freeMinutes {
            get {
                return this.freeMinutesField;
            }
            set {
                this.freeMinutesField = value;
            }
        }
        
        /// <remarks/>
        public string freeSeconds {
            get {
                return this.freeSecondsField;
            }
            set {
                this.freeSecondsField = value;
            }
        }
        
        /// <remarks/>
        public string balance1 {
            get {
                return this.balance1Field;
            }
            set {
                this.balance1Field = value;
            }
        }
        
        /// <remarks/>
        public string expirationDate1 {
            get {
                return this.expirationDate1Field;
            }
            set {
                this.expirationDate1Field = value;
            }
        }
        
        /// <remarks/>
        public string balance2 {
            get {
                return this.balance2Field;
            }
            set {
                this.balance2Field = value;
            }
        }
        
        /// <remarks/>
        public string expirationDate2 {
            get {
                return this.expirationDate2Field;
            }
            set {
                this.expirationDate2Field = value;
            }
        }
        
        /// <remarks/>
        public string plan {
            get {
                return this.planField;
            }
            set {
                this.planField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void wsbalanceEnquiry1CompletedEventHandler(object sender, wsbalanceEnquiry1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsbalanceEnquiry1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsbalanceEnquiry1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public balance1Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((balance1Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void wsbalanceEnquiry2CompletedEventHandler(object sender, wsbalanceEnquiry2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsbalanceEnquiry2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsbalanceEnquiry2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public balance2Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((balance2Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void wsbalanceEnquiry3CompletedEventHandler(object sender, wsbalanceEnquiry3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsbalanceEnquiry3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsbalanceEnquiry3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public balance3Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((balance3Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void wsbalanceEnquiry4CompletedEventHandler(object sender, wsbalanceEnquiry4CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsbalanceEnquiry4CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsbalanceEnquiry4CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public balance4Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((balance4Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void wsbalanceDiscount1CompletedEventHandler(object sender, wsbalanceDiscount1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsbalanceDiscount1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsbalanceDiscount1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public discount1Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((discount1Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void wsbalanceDiscount2CompletedEventHandler(object sender, wsbalanceDiscount2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsbalanceDiscount2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsbalanceDiscount2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public discount2Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((discount2Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void wsAddCreditCompletedEventHandler(object sender, wsAddCreditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsAddCreditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsAddCreditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public addCreditResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((addCreditResponse)(this.results[0]));
            }
        }
    }
}
#pragma warning restore 1591