//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace MW.MComm.WalletSolution.MComm.CarrierSim.PhoneManager {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PhoneManagerSoap", Namespace="http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StatusObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusinessObject))]
    public partial class PhoneManager : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DeleteOnePhoneOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteAllPhoneDataByCustomerIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOnePhoneOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllPhoneDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllPhoneDataByCustomerIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllPhoneDataByCriteriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetManyPhoneDataByCriteriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpsertOnePhoneOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOnePhoneByPhoneNumberOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PhoneManager() {
            this.Url = global::MW.MComm.WalletSolution.Properties.Settings.Default.MW_MComm_WalletSolution_MComm_CarrierSim_PhoneManager_PhoneManager;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DeleteOnePhoneCompletedEventHandler DeleteOnePhoneCompleted;
        
        /// <remarks/>
        public event DeleteAllPhoneDataByCustomerIDCompletedEventHandler DeleteAllPhoneDataByCustomerIDCompleted;
        
        /// <remarks/>
        public event GetOnePhoneCompletedEventHandler GetOnePhoneCompleted;
        
        /// <remarks/>
        public event GetAllPhoneDataCompletedEventHandler GetAllPhoneDataCompleted;
        
        /// <remarks/>
        public event GetAllPhoneDataByCustomerIDCompletedEventHandler GetAllPhoneDataByCustomerIDCompleted;
        
        /// <remarks/>
        public event GetAllPhoneDataByCriteriaCompletedEventHandler GetAllPhoneDataByCriteriaCompleted;
        
        /// <remarks/>
        public event GetManyPhoneDataByCriteriaCompletedEventHandler GetManyPhoneDataByCriteriaCompleted;
        
        /// <remarks/>
        public event UpsertOnePhoneCompletedEventHandler UpsertOnePhoneCompleted;
        
        /// <remarks/>
        public event GetOnePhoneByPhoneNumberCompletedEventHandler GetOnePhoneByPhoneNumberCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager/Delet" +
            "eOnePhone", RequestNamespace="http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager", ResponseNamespace="http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneResults DeleteOnePhone(Phone item, bool performCascadeOperation) {
            object[] results = this.Invoke("DeleteOnePhone", new object[] {
                        item,
                        performCascadeOperation});
            return ((PhoneResults)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteOnePhoneAsync(Phone item, bool performCascadeOperation) {
            this.DeleteOnePhoneAsync(item, performCascadeOperation, null);
        }
        
        /// <remarks/>
        public void DeleteOnePhoneAsync(Phone item, bool performCascadeOperation, object userState) {
            if ((this.DeleteOnePhoneOperationCompleted == null)) {
                this.DeleteOnePhoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOnePhoneOperationCompleted);
            }
            this.InvokeAsync("DeleteOnePhone", new object[] {
                        item,
                        performCascadeOperation}, this.DeleteOnePhoneOperationCompleted, userState);
        }
        
        private void OnDeleteOnePhoneOperationCompleted(object arg) {
            if ((this.DeleteOnePhoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteOnePhoneCompleted(this, new DeleteOnePhoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager/Delet" +
            "eAllPhoneDataByCustomerID", RequestNamespace="http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager", ResponseNamespace="http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneResults DeleteAllPhoneDataByCustomerID(string customerID) {
            object[] results = this.Invoke("DeleteAllPhoneDataByCustomerID", new object[] {
                        customerID});
            return ((PhoneResults)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAllPhoneDataByCustomerIDAsync(string customerID) {
            this.DeleteAllPhoneDataByCustomerIDAsync(customerID, null);
        }
        
        /// <remarks/>
        public void DeleteAllPhoneDataByCustomerIDAsync(string customerID, object userState) {
            if ((this.DeleteAllPhoneDataByCustomerIDOperationCompleted == null)) {
                this.DeleteAllPhoneDataByCustomerIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteAllPhoneDataByCustomerIDOperationCompleted);
            }
            this.InvokeAsync("DeleteAllPhoneDataByCustomerID", new object[] {
                        customerID}, this.DeleteAllPhoneDataByCustomerIDOperationCompleted, userState);
        }
        
        private void OnDeleteAllPhoneDataByCustomerIDOperationCompleted(object arg) {
            if ((this.DeleteAllPhoneDataByCustomerIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteAllPhoneDataByCustomerIDCompleted(this, new DeleteAllPhoneDataByCustomerIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager/GetOn" +
            "ePhone", RequestNamespace="http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager", ResponseNamespace="http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneResults GetOnePhone(string phoneID, string sortColumn, string sortDirection) {
            object[] results = this.Invoke("GetOnePhone", new object[] {
                        phoneID,
                        sortColumn,
                        sortDirection});
            return ((PhoneResults)(results[0]));
        }
        
        /// <remarks/>
        public void GetOnePhoneAsync(string phoneID, string sortColumn, string sortDirection) {
            this.GetOnePhoneAsync(phoneID, sortColumn, sortDirection, null);
        }
        
        /// <remarks/>
        public void GetOnePhoneAsync(string phoneID, string sortColumn, string sortDirection, object userState) {
            if ((this.GetOnePhoneOperationCompleted == null)) {
                this.GetOnePhoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOnePhoneOperationCompleted);
            }
            this.InvokeAsync("GetOnePhone", new object[] {
                        phoneID,
                        sortColumn,
                        sortDirection}, this.GetOnePhoneOperationCompleted, userState);
        }
        
        private void OnGetOnePhoneOperationCompleted(object arg) {
            if ((this.GetOnePhoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOnePhoneCompleted(this, new GetOnePhoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager/GetAl" +
            "lPhoneData", RequestNamespace="http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager", ResponseNamespace="http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneResults GetAllPhoneData(string sortColumn, string sortDirection) {
            object[] results = this.Invoke("GetAllPhoneData", new object[] {
                        sortColumn,
                        sortDirection});
            return ((PhoneResults)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllPhoneDataAsync(string sortColumn, string sortDirection) {
            this.GetAllPhoneDataAsync(sortColumn, sortDirection, null);
        }
        
        /// <remarks/>
        public void GetAllPhoneDataAsync(string sortColumn, string sortDirection, object userState) {
            if ((this.GetAllPhoneDataOperationCompleted == null)) {
                this.GetAllPhoneDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllPhoneDataOperationCompleted);
            }
            this.InvokeAsync("GetAllPhoneData", new object[] {
                        sortColumn,
                        sortDirection}, this.GetAllPhoneDataOperationCompleted, userState);
        }
        
        private void OnGetAllPhoneDataOperationCompleted(object arg) {
            if ((this.GetAllPhoneDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllPhoneDataCompleted(this, new GetAllPhoneDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager/GetAl" +
            "lPhoneDataByCustomerID", RequestNamespace="http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager", ResponseNamespace="http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneResults GetAllPhoneDataByCustomerID(string customerID, string sortColumn, string sortDirection) {
            object[] results = this.Invoke("GetAllPhoneDataByCustomerID", new object[] {
                        customerID,
                        sortColumn,
                        sortDirection});
            return ((PhoneResults)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllPhoneDataByCustomerIDAsync(string customerID, string sortColumn, string sortDirection) {
            this.GetAllPhoneDataByCustomerIDAsync(customerID, sortColumn, sortDirection, null);
        }
        
        /// <remarks/>
        public void GetAllPhoneDataByCustomerIDAsync(string customerID, string sortColumn, string sortDirection, object userState) {
            if ((this.GetAllPhoneDataByCustomerIDOperationCompleted == null)) {
                this.GetAllPhoneDataByCustomerIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllPhoneDataByCustomerIDOperationCompleted);
            }
            this.InvokeAsync("GetAllPhoneDataByCustomerID", new object[] {
                        customerID,
                        sortColumn,
                        sortDirection}, this.GetAllPhoneDataByCustomerIDOperationCompleted, userState);
        }
        
        private void OnGetAllPhoneDataByCustomerIDOperationCompleted(object arg) {
            if ((this.GetAllPhoneDataByCustomerIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllPhoneDataByCustomerIDCompleted(this, new GetAllPhoneDataByCustomerIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager/GetAl" +
            "lPhoneDataByCriteria", RequestNamespace="http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager", ResponseNamespace="http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneResults GetAllPhoneDataByCriteria(string lastModifiedDateStart, string lastModifiedDateEnd, string phoneNumber, string sortColumn, string sortDirection) {
            object[] results = this.Invoke("GetAllPhoneDataByCriteria", new object[] {
                        lastModifiedDateStart,
                        lastModifiedDateEnd,
                        phoneNumber,
                        sortColumn,
                        sortDirection});
            return ((PhoneResults)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllPhoneDataByCriteriaAsync(string lastModifiedDateStart, string lastModifiedDateEnd, string phoneNumber, string sortColumn, string sortDirection) {
            this.GetAllPhoneDataByCriteriaAsync(lastModifiedDateStart, lastModifiedDateEnd, phoneNumber, sortColumn, sortDirection, null);
        }
        
        /// <remarks/>
        public void GetAllPhoneDataByCriteriaAsync(string lastModifiedDateStart, string lastModifiedDateEnd, string phoneNumber, string sortColumn, string sortDirection, object userState) {
            if ((this.GetAllPhoneDataByCriteriaOperationCompleted == null)) {
                this.GetAllPhoneDataByCriteriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllPhoneDataByCriteriaOperationCompleted);
            }
            this.InvokeAsync("GetAllPhoneDataByCriteria", new object[] {
                        lastModifiedDateStart,
                        lastModifiedDateEnd,
                        phoneNumber,
                        sortColumn,
                        sortDirection}, this.GetAllPhoneDataByCriteriaOperationCompleted, userState);
        }
        
        private void OnGetAllPhoneDataByCriteriaOperationCompleted(object arg) {
            if ((this.GetAllPhoneDataByCriteriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllPhoneDataByCriteriaCompleted(this, new GetAllPhoneDataByCriteriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager/GetMa" +
            "nyPhoneDataByCriteria", RequestNamespace="http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager", ResponseNamespace="http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneResults GetManyPhoneDataByCriteria(string lastModifiedDateStart, string lastModifiedDateEnd, string phoneNumber, int startIndex, int pageSize, int maximumListSize, string sortColumn, string sortDirection) {
            object[] results = this.Invoke("GetManyPhoneDataByCriteria", new object[] {
                        lastModifiedDateStart,
                        lastModifiedDateEnd,
                        phoneNumber,
                        startIndex,
                        pageSize,
                        maximumListSize,
                        sortColumn,
                        sortDirection});
            return ((PhoneResults)(results[0]));
        }
        
        /// <remarks/>
        public void GetManyPhoneDataByCriteriaAsync(string lastModifiedDateStart, string lastModifiedDateEnd, string phoneNumber, int startIndex, int pageSize, int maximumListSize, string sortColumn, string sortDirection) {
            this.GetManyPhoneDataByCriteriaAsync(lastModifiedDateStart, lastModifiedDateEnd, phoneNumber, startIndex, pageSize, maximumListSize, sortColumn, sortDirection, null);
        }
        
        /// <remarks/>
        public void GetManyPhoneDataByCriteriaAsync(string lastModifiedDateStart, string lastModifiedDateEnd, string phoneNumber, int startIndex, int pageSize, int maximumListSize, string sortColumn, string sortDirection, object userState) {
            if ((this.GetManyPhoneDataByCriteriaOperationCompleted == null)) {
                this.GetManyPhoneDataByCriteriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetManyPhoneDataByCriteriaOperationCompleted);
            }
            this.InvokeAsync("GetManyPhoneDataByCriteria", new object[] {
                        lastModifiedDateStart,
                        lastModifiedDateEnd,
                        phoneNumber,
                        startIndex,
                        pageSize,
                        maximumListSize,
                        sortColumn,
                        sortDirection}, this.GetManyPhoneDataByCriteriaOperationCompleted, userState);
        }
        
        private void OnGetManyPhoneDataByCriteriaOperationCompleted(object arg) {
            if ((this.GetManyPhoneDataByCriteriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetManyPhoneDataByCriteriaCompleted(this, new GetManyPhoneDataByCriteriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager/Upser" +
            "tOnePhone", RequestNamespace="http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager", ResponseNamespace="http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneResults UpsertOnePhone(Phone item, bool performCascadeOperation) {
            object[] results = this.Invoke("UpsertOnePhone", new object[] {
                        item,
                        performCascadeOperation});
            return ((PhoneResults)(results[0]));
        }
        
        /// <remarks/>
        public void UpsertOnePhoneAsync(Phone item, bool performCascadeOperation) {
            this.UpsertOnePhoneAsync(item, performCascadeOperation, null);
        }
        
        /// <remarks/>
        public void UpsertOnePhoneAsync(Phone item, bool performCascadeOperation, object userState) {
            if ((this.UpsertOnePhoneOperationCompleted == null)) {
                this.UpsertOnePhoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpsertOnePhoneOperationCompleted);
            }
            this.InvokeAsync("UpsertOnePhone", new object[] {
                        item,
                        performCascadeOperation}, this.UpsertOnePhoneOperationCompleted, userState);
        }
        
        private void OnUpsertOnePhoneOperationCompleted(object arg) {
            if ((this.UpsertOnePhoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpsertOnePhoneCompleted(this, new UpsertOnePhoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager/GetOn" +
            "ePhoneByPhoneNumber", RequestNamespace="http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager", ResponseNamespace="http://modsystems.com/MW.MComm.CarrierSim.WebService/Customers/PhoneManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneResults GetOnePhoneByPhoneNumber(string phoneNumber, string sortColumn, string sortDirection) {
            object[] results = this.Invoke("GetOnePhoneByPhoneNumber", new object[] {
                        phoneNumber,
                        sortColumn,
                        sortDirection});
            return ((PhoneResults)(results[0]));
        }
        
        /// <remarks/>
        public void GetOnePhoneByPhoneNumberAsync(string phoneNumber, string sortColumn, string sortDirection) {
            this.GetOnePhoneByPhoneNumberAsync(phoneNumber, sortColumn, sortDirection, null);
        }
        
        /// <remarks/>
        public void GetOnePhoneByPhoneNumberAsync(string phoneNumber, string sortColumn, string sortDirection, object userState) {
            if ((this.GetOnePhoneByPhoneNumberOperationCompleted == null)) {
                this.GetOnePhoneByPhoneNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOnePhoneByPhoneNumberOperationCompleted);
            }
            this.InvokeAsync("GetOnePhoneByPhoneNumber", new object[] {
                        phoneNumber,
                        sortColumn,
                        sortDirection}, this.GetOnePhoneByPhoneNumberOperationCompleted, userState);
        }
        
        private void OnGetOnePhoneByPhoneNumberOperationCompleted(object arg) {
            if ((this.GetOnePhoneByPhoneNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOnePhoneByPhoneNumberCompleted(this, new GetOnePhoneByPhoneNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://modsystems.com/MW.MComm.CarrierSim/Customers/DataTypes")]
    public partial class Phone : PersistedBusinessObject {
        
        private string phoneNumberField;
        
        private System.Guid customerIDField;
        
        private float balanceField;
        
        private System.Guid phoneIDField;
        
        private string nameField;
        
        private float storedValueBalanceField;
        
        private float storedValueLockedBalanceField;
        
        public Phone() {
            this.phoneNumberField = "";
            this.balanceField = ((float)(0F));
            this.storedValueBalanceField = ((float)(0F));
            this.storedValueLockedBalanceField = ((float)(0F));
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid PhoneID {
            get {
                return this.phoneIDField;
            }
            set {
                this.phoneIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float StoredValueBalance {
            get {
                return this.storedValueBalanceField;
            }
            set {
                this.storedValueBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float StoredValueLockedBalance {
            get {
                return this.storedValueLockedBalanceField;
            }
            set {
                this.storedValueLockedBalanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Phone))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://modsystems.com/MW.MComm.CarrierSim/Customers/DataTypes")]
    public partial class PersistedBusinessObject : BusinessObject {
        
        private System.Nullable<System.Guid> createdByUserIDField;
        
        private System.Nullable<System.DateTime> createdDateField;
        
        private System.Nullable<System.Guid> lastModifiedByUserIDField;
        
        private System.Nullable<System.DateTime> lastModifiedDateField;
        
        private byte[] timestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> CreatedByUserID {
            get {
                return this.createdByUserIDField;
            }
            set {
                this.createdByUserIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> LastModifiedByUserID {
            get {
                return this.lastModifiedByUserIDField;
            }
            set {
                this.lastModifiedByUserIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersistedBusinessObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Phone))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://modsystems.com/MW.MComm.CarrierSim/Customers/DataTypes")]
    public partial class BusinessObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PhoneResults))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://modsystems.com/MW.MComm.CarrierSim/Customers/DataTypes")]
    public partial class StatusObject {
        
        private int statusCodeField;
        
        private string statusDescriptionField;
        
        private int totalRecordsField;
        
        private bool maximumListSizeExceededField;
        
        public StatusObject() {
            this.statusDescriptionField = "";
        }
        
        /// <remarks/>
        public int StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int TotalRecords {
            get {
                return this.totalRecordsField;
            }
            set {
                this.totalRecordsField = value;
            }
        }
        
        /// <remarks/>
        public bool MaximumListSizeExceeded {
            get {
                return this.maximumListSizeExceededField;
            }
            set {
                this.maximumListSizeExceededField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://modsystems.com/MW.MComm.CarrierSim/Customers/DataTypes")]
    public partial class PhoneResults : StatusObject {
        
        private Phone[] resultsField;
        
        /// <remarks/>
        public Phone[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void DeleteOnePhoneCompletedEventHandler(object sender, DeleteOnePhoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteOnePhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteOnePhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhoneResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhoneResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void DeleteAllPhoneDataByCustomerIDCompletedEventHandler(object sender, DeleteAllPhoneDataByCustomerIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteAllPhoneDataByCustomerIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteAllPhoneDataByCustomerIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhoneResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhoneResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetOnePhoneCompletedEventHandler(object sender, GetOnePhoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOnePhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOnePhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhoneResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhoneResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetAllPhoneDataCompletedEventHandler(object sender, GetAllPhoneDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllPhoneDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllPhoneDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhoneResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhoneResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetAllPhoneDataByCustomerIDCompletedEventHandler(object sender, GetAllPhoneDataByCustomerIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllPhoneDataByCustomerIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllPhoneDataByCustomerIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhoneResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhoneResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetAllPhoneDataByCriteriaCompletedEventHandler(object sender, GetAllPhoneDataByCriteriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllPhoneDataByCriteriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllPhoneDataByCriteriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhoneResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhoneResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetManyPhoneDataByCriteriaCompletedEventHandler(object sender, GetManyPhoneDataByCriteriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetManyPhoneDataByCriteriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetManyPhoneDataByCriteriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhoneResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhoneResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void UpsertOnePhoneCompletedEventHandler(object sender, UpsertOnePhoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpsertOnePhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpsertOnePhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhoneResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhoneResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetOnePhoneByPhoneNumberCompletedEventHandler(object sender, GetOnePhoneByPhoneNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOnePhoneByPhoneNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOnePhoneByPhoneNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhoneResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhoneResults)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591