//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace MW.MComm.WalletSolution.MComm.Ganadero.Simulator {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://www.bg.com.bo/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CustomerInformationOperationCompleted;
        
        private System.Threading.SendOrPostCallback AccountInformationOperationCompleted;
        
        private System.Threading.SendOrPostCallback AccountInformation2OperationCompleted;
        
        private System.Threading.SendOrPostCallback CurrencyConversionCalculationOperationCompleted;
        
        private System.Threading.SendOrPostCallback AccountTransferOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::MW.MComm.WalletSolution.Properties.Settings.Default.MW_MComm_WalletSolution_MComm_Ganadero_Simulator_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CustomerInformationCompletedEventHandler CustomerInformationCompleted;
        
        /// <remarks/>
        public event AccountInformationCompletedEventHandler AccountInformationCompleted;
        
        /// <remarks/>
        public event AccountInformation2CompletedEventHandler AccountInformation2Completed;
        
        /// <remarks/>
        public event CurrencyConversionCalculationCompletedEventHandler CurrencyConversionCalculationCompleted;
        
        /// <remarks/>
        public event AccountTransferCompletedEventHandler AccountTransferCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bg.com.bo/CustomerInformation", RequestNamespace="http://www.bg.com.bo/", ResponseNamespace="http://www.bg.com.bo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomerInformationResult CustomerInformation(string CustomerCode, string CustomerPin, string AuditId) {
            object[] results = this.Invoke("CustomerInformation", new object[] {
                        CustomerCode,
                        CustomerPin,
                        AuditId});
            return ((CustomerInformationResult)(results[0]));
        }
        
        /// <remarks/>
        public void CustomerInformationAsync(string CustomerCode, string CustomerPin, string AuditId) {
            this.CustomerInformationAsync(CustomerCode, CustomerPin, AuditId, null);
        }
        
        /// <remarks/>
        public void CustomerInformationAsync(string CustomerCode, string CustomerPin, string AuditId, object userState) {
            if ((this.CustomerInformationOperationCompleted == null)) {
                this.CustomerInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomerInformationOperationCompleted);
            }
            this.InvokeAsync("CustomerInformation", new object[] {
                        CustomerCode,
                        CustomerPin,
                        AuditId}, this.CustomerInformationOperationCompleted, userState);
        }
        
        private void OnCustomerInformationOperationCompleted(object arg) {
            if ((this.CustomerInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CustomerInformationCompleted(this, new CustomerInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bg.com.bo/AccountInformation", RequestNamespace="http://www.bg.com.bo/", ResponseNamespace="http://www.bg.com.bo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccountInformationResult AccountInformation(string CustomerCode, string CustomerPin, string AuditId, int AccountNumber) {
            object[] results = this.Invoke("AccountInformation", new object[] {
                        CustomerCode,
                        CustomerPin,
                        AuditId,
                        AccountNumber});
            return ((AccountInformationResult)(results[0]));
        }
        
        /// <remarks/>
        public void AccountInformationAsync(string CustomerCode, string CustomerPin, string AuditId, int AccountNumber) {
            this.AccountInformationAsync(CustomerCode, CustomerPin, AuditId, AccountNumber, null);
        }
        
        /// <remarks/>
        public void AccountInformationAsync(string CustomerCode, string CustomerPin, string AuditId, int AccountNumber, object userState) {
            if ((this.AccountInformationOperationCompleted == null)) {
                this.AccountInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccountInformationOperationCompleted);
            }
            this.InvokeAsync("AccountInformation", new object[] {
                        CustomerCode,
                        CustomerPin,
                        AuditId,
                        AccountNumber}, this.AccountInformationOperationCompleted, userState);
        }
        
        private void OnAccountInformationOperationCompleted(object arg) {
            if ((this.AccountInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccountInformationCompleted(this, new AccountInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bg.com.bo/AccountInformation2", RequestNamespace="http://www.bg.com.bo/", ResponseNamespace="http://www.bg.com.bo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccountInformationResult AccountInformation2(string CustomerCode, string CustomerPin, string AuditId, string AccountCod) {
            object[] results = this.Invoke("AccountInformation2", new object[] {
                        CustomerCode,
                        CustomerPin,
                        AuditId,
                        AccountCod});
            return ((AccountInformationResult)(results[0]));
        }
        
        /// <remarks/>
        public void AccountInformation2Async(string CustomerCode, string CustomerPin, string AuditId, string AccountCod) {
            this.AccountInformation2Async(CustomerCode, CustomerPin, AuditId, AccountCod, null);
        }
        
        /// <remarks/>
        public void AccountInformation2Async(string CustomerCode, string CustomerPin, string AuditId, string AccountCod, object userState) {
            if ((this.AccountInformation2OperationCompleted == null)) {
                this.AccountInformation2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccountInformation2OperationCompleted);
            }
            this.InvokeAsync("AccountInformation2", new object[] {
                        CustomerCode,
                        CustomerPin,
                        AuditId,
                        AccountCod}, this.AccountInformation2OperationCompleted, userState);
        }
        
        private void OnAccountInformation2OperationCompleted(object arg) {
            if ((this.AccountInformation2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccountInformation2Completed(this, new AccountInformation2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bg.com.bo/CurrencyConversionCalculation", RequestNamespace="http://www.bg.com.bo/", ResponseNamespace="http://www.bg.com.bo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CurrencyConversionCalculationResult CurrencyConversionCalculation(string OriginalCurrency, string DestinationCurrency, string Type, decimal Amount, string CustomerCode) {
            object[] results = this.Invoke("CurrencyConversionCalculation", new object[] {
                        OriginalCurrency,
                        DestinationCurrency,
                        Type,
                        Amount,
                        CustomerCode});
            return ((CurrencyConversionCalculationResult)(results[0]));
        }
        
        /// <remarks/>
        public void CurrencyConversionCalculationAsync(string OriginalCurrency, string DestinationCurrency, string Type, decimal Amount, string CustomerCode) {
            this.CurrencyConversionCalculationAsync(OriginalCurrency, DestinationCurrency, Type, Amount, CustomerCode, null);
        }
        
        /// <remarks/>
        public void CurrencyConversionCalculationAsync(string OriginalCurrency, string DestinationCurrency, string Type, decimal Amount, string CustomerCode, object userState) {
            if ((this.CurrencyConversionCalculationOperationCompleted == null)) {
                this.CurrencyConversionCalculationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCurrencyConversionCalculationOperationCompleted);
            }
            this.InvokeAsync("CurrencyConversionCalculation", new object[] {
                        OriginalCurrency,
                        DestinationCurrency,
                        Type,
                        Amount,
                        CustomerCode}, this.CurrencyConversionCalculationOperationCompleted, userState);
        }
        
        private void OnCurrencyConversionCalculationOperationCompleted(object arg) {
            if ((this.CurrencyConversionCalculationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CurrencyConversionCalculationCompleted(this, new CurrencyConversionCalculationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bg.com.bo/AccountTransfer", RequestNamespace="http://www.bg.com.bo/", ResponseNamespace="http://www.bg.com.bo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccountTransferResult AccountTransfer(string CustomerCode, string CustomerPin, string AuditId, string OriginAccountCode, string DestinationAccountCode, decimal Ammount, string TransactionCurrency) {
            object[] results = this.Invoke("AccountTransfer", new object[] {
                        CustomerCode,
                        CustomerPin,
                        AuditId,
                        OriginAccountCode,
                        DestinationAccountCode,
                        Ammount,
                        TransactionCurrency});
            return ((AccountTransferResult)(results[0]));
        }
        
        /// <remarks/>
        public void AccountTransferAsync(string CustomerCode, string CustomerPin, string AuditId, string OriginAccountCode, string DestinationAccountCode, decimal Ammount, string TransactionCurrency) {
            this.AccountTransferAsync(CustomerCode, CustomerPin, AuditId, OriginAccountCode, DestinationAccountCode, Ammount, TransactionCurrency, null);
        }
        
        /// <remarks/>
        public void AccountTransferAsync(string CustomerCode, string CustomerPin, string AuditId, string OriginAccountCode, string DestinationAccountCode, decimal Ammount, string TransactionCurrency, object userState) {
            if ((this.AccountTransferOperationCompleted == null)) {
                this.AccountTransferOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccountTransferOperationCompleted);
            }
            this.InvokeAsync("AccountTransfer", new object[] {
                        CustomerCode,
                        CustomerPin,
                        AuditId,
                        OriginAccountCode,
                        DestinationAccountCode,
                        Ammount,
                        TransactionCurrency}, this.AccountTransferOperationCompleted, userState);
        }
        
        private void OnAccountTransferOperationCompleted(object arg) {
            if ((this.AccountTransferCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccountTransferCompleted(this, new AccountTransferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bg.com.bo/")]
    public partial class CustomerInformationResult {
        
        private string customerNameField;
        
        private string customerTypeField;
        
        private int accountCountField;
        
        private int registeredBillerCountField;
        
        private int errorCodeField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerType {
            get {
                return this.customerTypeField;
            }
            set {
                this.customerTypeField = value;
            }
        }
        
        /// <remarks/>
        public int AccountCount {
            get {
                return this.accountCountField;
            }
            set {
                this.accountCountField = value;
            }
        }
        
        /// <remarks/>
        public int RegisteredBillerCount {
            get {
                return this.registeredBillerCountField;
            }
            set {
                this.registeredBillerCountField = value;
            }
        }
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bg.com.bo/")]
    public partial class AccountTransferResult {
        
        private decimal iTFOriginAccountField;
        
        private decimal iTFDestinationAccountField;
        
        private string confirmationCodeField;
        
        private int errorCodeField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        public decimal ITFOriginAccount {
            get {
                return this.iTFOriginAccountField;
            }
            set {
                this.iTFOriginAccountField = value;
            }
        }
        
        /// <remarks/>
        public decimal ITFDestinationAccount {
            get {
                return this.iTFDestinationAccountField;
            }
            set {
                this.iTFDestinationAccountField = value;
            }
        }
        
        /// <remarks/>
        public string ConfirmationCode {
            get {
                return this.confirmationCodeField;
            }
            set {
                this.confirmationCodeField = value;
            }
        }
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bg.com.bo/")]
    public partial class CurrencyConversionCalculationResult {
        
        private decimal exchangeRateField;
        
        private decimal significativeDigitsField;
        
        private decimal destinationAmmountField;
        
        private int errorCodeField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        public decimal ExchangeRate {
            get {
                return this.exchangeRateField;
            }
            set {
                this.exchangeRateField = value;
            }
        }
        
        /// <remarks/>
        public decimal SignificativeDigits {
            get {
                return this.significativeDigitsField;
            }
            set {
                this.significativeDigitsField = value;
            }
        }
        
        /// <remarks/>
        public decimal DestinationAmmount {
            get {
                return this.destinationAmmountField;
            }
            set {
                this.destinationAmmountField = value;
            }
        }
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bg.com.bo/")]
    public partial class AccountInformationResult {
        
        private string accountCodeField;
        
        private string accountTypeField;
        
        private decimal accountBalanceField;
        
        private decimal accountDailyLimitField;
        
        private string accountCurrencyField;
        
        private int errorCodeField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        public string AccountCode {
            get {
                return this.accountCodeField;
            }
            set {
                this.accountCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AccountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
            }
        }
        
        /// <remarks/>
        public decimal AccountBalance {
            get {
                return this.accountBalanceField;
            }
            set {
                this.accountBalanceField = value;
            }
        }
        
        /// <remarks/>
        public decimal AccountDailyLimit {
            get {
                return this.accountDailyLimitField;
            }
            set {
                this.accountDailyLimitField = value;
            }
        }
        
        /// <remarks/>
        public string AccountCurrency {
            get {
                return this.accountCurrencyField;
            }
            set {
                this.accountCurrencyField = value;
            }
        }
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void CustomerInformationCompletedEventHandler(object sender, CustomerInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomerInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CustomerInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerInformationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerInformationResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void AccountInformationCompletedEventHandler(object sender, AccountInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccountInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccountInformationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccountInformationResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void AccountInformation2CompletedEventHandler(object sender, AccountInformation2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountInformation2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccountInformation2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccountInformationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccountInformationResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void CurrencyConversionCalculationCompletedEventHandler(object sender, CurrencyConversionCalculationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CurrencyConversionCalculationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CurrencyConversionCalculationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CurrencyConversionCalculationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CurrencyConversionCalculationResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void AccountTransferCompletedEventHandler(object sender, AccountTransferCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountTransferCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccountTransferCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccountTransferResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccountTransferResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591