
/*<copyright>
Meta Wallet, Inc (c) 2007 All Rights Reserved.
720 3rd Ave #1100, Seattle WA 98104 - (206) 973-1036
All Rights Reserved, (c) 2007, covered by Trademark Laws, contents are considered Restricted Secrets by Meta Wallet.  The contents also may only be viewed by Meta Wallet Engineers (employees) and selected partners as outlined in the Licensing Agreement between Meta Wallet and said partners.
No copying, printing, distribution, or transmission of any contents allowed.  No 3rd Party may open, read, or have access to any part or whole of software source code, configuration files, log files or performance information, including process naming conventions or benchmarks.
No rights to reproduce this software, configuration files, of log files are granted.  Unauthorized use or disclosure of this information could impact Meta Wallet's competitive advantage.
Information in this document is considered trade secret.  No license, expressed or implied, by estoppel or otherwise, to any intellectual property rights is granted in this source code, configuration file, or log file.
</copyright>*/
using System;
using System.Xml;
using System.Xml.Serialization;
using System.ComponentModel;
using MOD.Data;
using MW.MComm.WalletSolution.BLL.Config;
using BLL = MW.MComm.WalletSolution.BLL;
using Utility = MW.MComm.WalletSolution.Utility;
using Microsoft.Practices.EnterpriseLibrary.ExceptionHandling;
namespace MW.MComm.WalletSolution.BLL.UserExperience
{
  // ------------------------------------------------------------------------------
  /// <summary>This enumeration is for holding known SiteLabelDefinition codes.</summary>
  ///
  /// <remarks></remarks>
  // ------------------------------------------------------------------------------
  public enum SiteLabelDefinitionCode
  {
    AcceptButtonLabel = 73,
    Account = 36,
    AccountBalance = 42,
    AccountCurrency = 37,
    AccountDescription = 39,
    AccountType = 38,
    AccountsTitle = 21,
    AddBankAccountsLabel = 70,
    AddCreditButtonLabel = 94,
    AddressLabel = 63,
    AmountLabel = 87,
    AmountReceivedLabel = 92,
    AmounttotransferLabel = 137,
    ApproveButtonLabel = 17,
    ApproveOrderResponseTitle = 19,
    ApproveOrderTitle = 13,
    Balance = 79,
    BalanceWasDeducedBs = 131,
    BetaMode = 115,
    BolivianosLabel = 11,
    BothAccountsMustBeSelected = 449,
    BothAccountsMustBeSpecified = 451,
    BothSelectedAccountsCantBeTheSame = 450,
    BuyButtonLabel = 88,
    BuyPrePaidMinutesSuccessful = 429,
    BuyPrepaidFormTitle = 84,
    BuyPrepaidMinutesLink = 109,
    CancelButtonLabel = 74,
    CarrierPrepaidBalance = 81,
    CashierApplication = 91,
    CashierLink = 111,
    ChangeAccountLabel = 55,
    ChangeAccountSuccess = 57,
    ChangeDefaulAccountButton = 53,
    ChangeLanguageButton = 54,
    ChangeLanguageLabel = 56,
    ChangePINButtonLabel = 47,
    ChangePINparametersIncorrect = 412,
    ClientBalanceWasAddedBs = 130,
    ConfirmPINAndPhoneNumber = 103,
    ContinueButtonLabel = 95,
    CreateAccountButtonLabel = 102,
    CreateStoredValueAccount = 69,
    CreditOnYourPhone = 128,
    CurrentBalanceResellingCredit = 127,
    Customer = 98,
    CustomerNotFound = 421,
    CustomerphoneLabel = 124,
    DemoMode = 112,
    DestinationPhoneNumberLabel = 85,
    DestinationTelephoneInputLabel = 8,
    DifferentAmountLabel = 123,
    EmailLabel = 65,
    EnterAValidAmount = 426,
    EnterBankPin = 41,
    EnterYourBankCustomerCodeLabel = 76,
    EnterYourBankPINLabel = 77,
    ErrorCreatingTheAccount = 82,
    ErrorPhoneAlredyRegistered = 413,
    ExcededAmount = 439,
    ExternalPinError = 406,
    FeatureUnavailable = 51,
    For = 118,
    FormValidationFailure = 29,
    From = 129,
    Help = 105,
    HelpPageLink = 2,
    HighSecurity = 113,
    HomePageLink = 1,
    InsufficientBalanceInStoredValueAccount = 418,
    InvalidCustomerPhone = 440,
    InvalidPhone = 446,
    InvallidAmount = 438,
    IsNotAReseller = 99,
    Label = 126,
    LeavePhoneNumberBlankLabel = 86,
    LinkExpired = 424,
    LogInButtonLabel = 58,
    LogInHighSecurityLabel = 61,
    LogInLowSecurityLabel = 60,
    LogInSecurityLevel = 59,
    LoginAcceptedPushLink = 33,
    LoginAcceptedWaitForLink = 31,
    LoginFailed = 32,
    LoginLabel = 104,
    LoginPhoneLabel = 30,
    LogoutButton = 43,
    ManageAccountsLink = 25,
    ManageAccountsTitle = 26,
    Memo = 139,
    MetaWalletHeader = 27,
    MetaWalletTagline = 28,
    MobileFormsTitle = 34,
    NameLabel = 64,
    NegativeAmountEntered = 425,
    NewAccountLink = 3,
    NewAccountTitle = 23,
    NewBalance = 101,
    NoBankAccount = 433,
    NoNewAccountsWereFound = 83,
    None = 0,
    NotEnoughBalance = 423,
    NotFound = 97,
    NotProcessRequest = 435,
    NotStoredValueAccount = 436,
    NotificationError = 401,
    OKButtonLabel = 24,
    OptionalDescriptionForNewAccountLabel = 78,
    OrderErrorNoAccounts = 403,
    OrderErrorNotEnoughBalance = 405,
    OrderErrorUnknownPhone = 404,
    OrderErrorUnspecifiedAccount = 410,
    OrderErrorUnspecifiedAmount = 407,
    OrderErrorUnspecifiedDestination = 408,
    OrderErrorUnspecifiedPIN = 409,
    OrderProcessed = 45,
    OrderProcessingError = 402,
    OtherAmount = 122,
    OtherOptions = 62,
    PINAccepted = 114,
    PINLabel = 14,
    PINhasBeenChanged = 52,
    PaymentAmountLabel = 9,
    PaymentReceivedSMS = 44,
    PaymentRequestedFrom = 116,
    PhoneNotFound = 420,
    PleaseEnterValidAmount = 448,
    PostPaidNote = 40,
    ReceiveButtonLabel = 16,
    RecevingPhoneNotFound = 428,
    RejectButtonLabel = 18,
    RejectOrderResponseTitle = 20,
    Reseller = 96,
    ResellerApplication = 120,
    ResellerBalanceWasAdded = 100,
    ResellerLink = 110,
    ResellerNumberLabel = 93,
    ResellerWithoutAValueAccount = 430,
    SelectAParticipatingBankLabel = 75,
    SelectAccountToCredit = 134,
    SelectAccountToDebitFrom = 90,
    SelectAnAccount = 68,
    SelectSourceAccount = 46,
    SelectTheAccountAccountList = 89,
    SelfTransfer = 140,
    SellButtonLabel = 125,
    SellCredit = 121,
    SendAndReceiveLink = 5,
    SendAndReceiveResponseTitle = 12,
    SendAndReceiveTitle = 6,
    SendBankTransferLink = 106,
    SendButtonLabel = 15,
    SessionExpired = 432,
    SessionTimeOut = 431,
    ShowAccountHistory = 150,
    SourceTelephoneInputLabel = 7,
    SpecifyAValidAmount = 445,
    SpecifyAccountToTransferFrom = 442,
    StoredValueAccountAtMWCarrier = 67,
    StoredValueDefaultAccount = 66,
    StoredValueTransactionsFormTitle = 132,
    StoredValueTransactionsLink = 108,
    TermsAndConditionsLabel = 71,
    TermsLabel = 72,
    ThisPhoneNumberIsAlreadyRegistered = 419,
    To = 117,
    TransferAmountMustBeAPositiveNumber = 417,
    TransferButtonLabel = 135,
    TransferFundsBetweenMyAccountsLink = 107,
    TransferStoredValueLabel = 133,
    TransferSuccesful = 136,
    TypeCurrentPIN = 48,
    TypeNewPIN = 49,
    TypeNewPINAgain = 50,
    USDollarsLabel = 10,
    USDviaMetawallet = 138,
    UnableToFindAccount = 427,
    UnableToIdentifyValueAccount = 444,
    UnableToPerformTransfer = 447,
    UnableToProcessTransaction = 441,
    UnableToReadAmount = 437,
    UnableToRetrieveBalance = 80,
    UnableToRetrieveBalanceFromBank = 415,
    UnableToRetrieveCustomerData = 414,
    UnableToRetrieveCustomerDataFromCarrier = 422,
    UnableToRetrieveStoredValueBalanceFromPartner = 416,
    UnspecifiedException = 411,
    UserPreferencesLink = 4,
    UserPreferencesTitle = 22,
    UserWithoutValueAccount = 443,
    WasPaidFrom = 119,
    WelcomeLabel = 35,
  }
}