//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591
namespace MW.MComm.WalletSolution.MComm.Nuevatel.ClientInformation {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ClientInformationPortBinding", Namespace="http://www.nuevatel.com")]
    public partial class ClientInfoService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getInformationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ClientInfoService() {
            this.Url = global::MW.MComm.WalletSolution.Properties.Settings.Default.MW_MComm_WalletSolution_MComm_Nuevatel_ClientInformation_ClientInfoService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getInformationCompletedEventHandler getInformationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.nuevatel.com", ResponseNamespace="http://www.nuevatel.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public consumptionEntityServicesForClient getInformation([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string user, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string phoneNumber) {
            object[] results = this.Invoke("getInformation", new object[] {
                        user,
                        password,
                        phoneNumber});
            return ((consumptionEntityServicesForClient)(results[0]));
        }
        
        /// <remarks/>
        public void getInformationAsync(string user, string password, string phoneNumber) {
            this.getInformationAsync(user, password, phoneNumber, null);
        }
        
        /// <remarks/>
        public void getInformationAsync(string user, string password, string phoneNumber, object userState) {
            if ((this.getInformationOperationCompleted == null)) {
                this.getInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInformationOperationCompleted);
            }
            this.InvokeAsync("getInformation", new object[] {
                        user,
                        password,
                        phoneNumber}, this.getInformationOperationCompleted, userState);
        }
        
        private void OngetInformationOperationCompleted(object arg) {
            if ((this.getInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInformationCompleted(this, new getInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nuevatel.com")]
    public partial class consumptionEntityServicesForClient {
        
        private string billingPersonDateOfBirthField;
        
        private string billingPersonDocumentField;
        
        private string billingPersonFullNameField;
        
        private string billingPersonHouseAddressField;
        
        private string billingPersonNitField;
        
        private string billingPersonSexField;
        
        private string billingPersonTypeField;
        
        private string billingPersonWorkAddressField;
        
        private string clientDateOfBirthField;
        
        private string clientDocumentField;
        
        private string clientFullNameField;
        
        private string clientHouseAddressField;
        
        private string clientNitField;
        
        private string clientPersonTypeField;
        
        private string clientSexField;
        
        private string clientWorkAddressField;
        
        private string consEntityDateOfBirthField;
        
        private string consEntityDocumentField;
        
        private string consEntityFullNameField;
        
        private string consEntityHouseAddressField;
        
        private string consEntityLineStateField;
        
        private string consEntityNitField;
        
        private string consEntityPersonTypeField;
        
        private string consEntityPhoneNumberField;
        
        private string consEntityPlanField;
        
        private string consEntitySexField;
        
        private string consEntityWorkAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string billingPersonDateOfBirth {
            get {
                return this.billingPersonDateOfBirthField;
            }
            set {
                this.billingPersonDateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string billingPersonDocument {
            get {
                return this.billingPersonDocumentField;
            }
            set {
                this.billingPersonDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string billingPersonFullName {
            get {
                return this.billingPersonFullNameField;
            }
            set {
                this.billingPersonFullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string billingPersonHouseAddress {
            get {
                return this.billingPersonHouseAddressField;
            }
            set {
                this.billingPersonHouseAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string billingPersonNit {
            get {
                return this.billingPersonNitField;
            }
            set {
                this.billingPersonNitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string billingPersonSex {
            get {
                return this.billingPersonSexField;
            }
            set {
                this.billingPersonSexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string billingPersonType {
            get {
                return this.billingPersonTypeField;
            }
            set {
                this.billingPersonTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string billingPersonWorkAddress {
            get {
                return this.billingPersonWorkAddressField;
            }
            set {
                this.billingPersonWorkAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientDateOfBirth {
            get {
                return this.clientDateOfBirthField;
            }
            set {
                this.clientDateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientDocument {
            get {
                return this.clientDocumentField;
            }
            set {
                this.clientDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientFullName {
            get {
                return this.clientFullNameField;
            }
            set {
                this.clientFullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientHouseAddress {
            get {
                return this.clientHouseAddressField;
            }
            set {
                this.clientHouseAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientNit {
            get {
                return this.clientNitField;
            }
            set {
                this.clientNitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientPersonType {
            get {
                return this.clientPersonTypeField;
            }
            set {
                this.clientPersonTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientSex {
            get {
                return this.clientSexField;
            }
            set {
                this.clientSexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientWorkAddress {
            get {
                return this.clientWorkAddressField;
            }
            set {
                this.clientWorkAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consEntityDateOfBirth {
            get {
                return this.consEntityDateOfBirthField;
            }
            set {
                this.consEntityDateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consEntityDocument {
            get {
                return this.consEntityDocumentField;
            }
            set {
                this.consEntityDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consEntityFullName {
            get {
                return this.consEntityFullNameField;
            }
            set {
                this.consEntityFullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consEntityHouseAddress {
            get {
                return this.consEntityHouseAddressField;
            }
            set {
                this.consEntityHouseAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consEntityLineState {
            get {
                return this.consEntityLineStateField;
            }
            set {
                this.consEntityLineStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consEntityNit {
            get {
                return this.consEntityNitField;
            }
            set {
                this.consEntityNitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consEntityPersonType {
            get {
                return this.consEntityPersonTypeField;
            }
            set {
                this.consEntityPersonTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consEntityPhoneNumber {
            get {
                return this.consEntityPhoneNumberField;
            }
            set {
                this.consEntityPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consEntityPlan {
            get {
                return this.consEntityPlanField;
            }
            set {
                this.consEntityPlanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consEntitySex {
            get {
                return this.consEntitySexField;
            }
            set {
                this.consEntitySexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consEntityWorkAddress {
            get {
                return this.consEntityWorkAddressField;
            }
            set {
                this.consEntityWorkAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getInformationCompletedEventHandler(object sender, getInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public consumptionEntityServicesForClient Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((consumptionEntityServicesForClient)(this.results[0]));
            }
        }
    }
}
#pragma warning restore 1591